# Generated by Django 5.1.2 on 2024-11-06 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nailo_BE", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="designs",
            old_name="design_image",
            new_name="design_url",
        ),
        migrations.RenameField(
            model_name="shops",
            old_name="intro_image",
            new_name="shops_url",
        ),
    ]
