# Generated by Django 5.1.2 on 2024-11-25 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nailo_be", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TryOnHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_image", models.ImageField(upload_to="tryon/original/")),
                ("predicted_image", models.ImageField(upload_to="tryon/predicted/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nailo_be.customers",
                    ),
                ),
            ],
        ),
    ]
