# Generated by Django 5.1.2 on 2024-11-06 01:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nailo_BE", "0002_rename_design_image_designs_design_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="request_key",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="response_key",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
