# Generated by Django 5.1.2 on 2024-11-15 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nailo_BE", "0002_rename_design_image_designs_design_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="designs",
            name="like_count",
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("liked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="like",
                        to="nailo_BE.customers",
                    ),
                ),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="like",
                        to="nailo_BE.designs",
                    ),
                ),
            ],
        ),
    ]
