# Generated by Django 5.1.2 on 2024-11-07 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nailo_BE", "0003_alter_request_request_key_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shops",
            old_name="shopper_id",
            new_name="shop_id",
        ),
        migrations.RenameField(
            model_name="shops",
            old_name="shopper_key",
            new_name="shop_key",
        ),
        migrations.RenameField(
            model_name="shops",
            old_name="shopper_name",
            new_name="shop_name",
        ),
        migrations.RenameField(
            model_name="shops",
            old_name="shops_url",
            new_name="shop_url",
        ),
    ]
