# Generated by Django 5.1.2 on 2024-11-07 05:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nailo_BE", "0003_alter_request_request_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customers",
            name="customer_key",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
