# Generated by Django 5.1.2 on 2024-11-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nailo_be", "0003_designs_like_count_like"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("customer", "design")},
        ),
    ]
