# Generated by Django 5.1.2 on 2024-11-16 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nailo_be", "0004_alter_like_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customers",
            name="customer_pw",
        ),
        migrations.RemoveField(
            model_name="customers",
            name="design_book",
        ),
        migrations.RemoveField(
            model_name="customers",
            name="is_active",
        ),
    ]
