# Generated by Django 5.1.2 on 2024-11-21 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nailo_be", "0005_remove_customers_customer_pw_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="designs",
            name="tag",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="designs",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="nailo_be.shops"
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="design",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liked_design",
                to="nailo_be.designs",
            ),
        ),
    ]
